from fastapi import APIRouter, HTTPException
from typing import List, Optional
from datetime import datetime
import uuid

# Fix relative imports to absolute imports
from models.project import Project, ProjectCreate, ProjectStatus, ProjectUpdate
from models.agent import Agent, AgentRole
from models.deliverable import Deliverable, DeliverableType, CodeFile
from services.orchestrator_service import OrchestratorService
from services.project_service import ProjectService

router = APIRouter()
orchestrator = OrchestratorService()
project_service = ProjectService()

@router.post("/", response_model=Project)
async def create_project(project_create: ProjectCreate):
    """Create a new project and initialize CTO agent"""
    try:
        # Create project
        project = Project(
            id=str(uuid.uuid4()),
            status=ProjectStatus.PLANNING,
            created_at=datetime.now(),
            updated_at=datetime.now(),
            **project_create.dict()
        )
        
        # Plan project and create agents
        planned_project = await orchestrator.plan_project(project)
        
        # Store project
        await project_service.create_project(planned_project)
        
        return planned_project
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to create project: {str(e)}")

@router.get("/", response_model=List[Project])
async def get_projects():
    """Get all projects"""
    return await project_service.get_all_projects()

@router.get("/{project_id}", response_model=Project)
async def get_project(project_id: str):
    """Get a specific project"""
    project = await project_service.get_project(project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    return project

@router.get("/{project_id}/agents", response_model=List[Agent])
async def get_project_agents(project_id: str):
    """Get all agents for a project"""
    return await project_service.get_project_agents(project_id)

@router.get("/{project_id}/deliverables", response_model=List[Deliverable])
async def get_project_deliverables(project_id: str):
    """Get all deliverables for a project"""
    return await project_service.get_project_deliverables(project_id)

@router.get("/{project_id}/code", response_model=List[CodeFile])
async def get_project_code(project_id: str):
    """Get all code files generated by agents for a project"""
    try:
        # Get all agents for the project
        project_agents = await project_service.get_project_agents(project_id)
        code_files = []
        
        print(f"🔍 Getting code for project {project_id}, found {len(project_agents)} agents")
        
        # Collect generated code from all agents
        for agent in project_agents:
            if agent.generated_code:
                print(f"📝 Agent {agent.role.value} has generated code: {agent.generated_code['filename']}")
                
                code_file = CodeFile(
                    id=f"{project_id}-{agent.role.value}-code",
                    filename=agent.generated_code['filename'],
                    file_path=f"src/{agent.generated_code['filename']}" if agent.generated_code['type'] == 'frontend' 
                             else f"backend/{agent.generated_code['filename']}" if agent.generated_code['type'] == 'backend'
                             else f"database/{agent.generated_code['filename']}" if agent.generated_code['type'] == 'database'
                             else agent.generated_code['filename'],
                    content=agent.generated_code['content'],
                    language='typescript' if agent.generated_code['type'] == 'frontend' 
                            else 'python' if agent.generated_code['type'] == 'backend'
                            else 'sql' if agent.generated_code['type'] == 'database'
                            else 'yaml',
                    agent_id=agent.id,
                    project_id=project_id,
                    created_at=agent.updated_at,
                    updated_at=agent.updated_at
                )
                code_files.append(code_file)
            else:
                print(f"⚠️ Agent {agent.role.value} has no generated code yet")
        
        print(f"✅ Returning {len(code_files)} code files for project {project_id}")
        return code_files
        
    except Exception as e:
        print(f"❌ Error getting project code: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to get project code: {str(e)}")

@router.post("/{project_id}/chat")
async def chat_with_cto(project_id: str, message: str):
    """Chat with the CTO agent for a project"""
    try:
        # Get project and CTO agent
        project = await project_service.get_project(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")
        
        agents = await project_service.get_project_agents(project_id)
        cto_agent = next((a for a in agents if a.role == AgentRole.CTO), None)
        
        if not cto_agent:
            raise HTTPException(status_code=404, detail="CTO agent not found")
        
        # Process message through orchestrator
        response = await orchestrator.process_message(cto_agent.id, message)
        
        return {
            "response": response,
            "agent_id": cto_agent.id,
            "project_id": project_id
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Chat failed: {str(e)}")

@router.post("/{project_id}/execute")
async def execute_project(project_id: str):
    """Execute the project by running all agents"""
    try:
        print(f"API: Executing project {project_id}")
        
        project = await project_service.get_project(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")
        
        # Execute project through orchestrator
        result = await orchestrator.execute_project(project_id)
        print(f"API: Orchestrator execution result: {result}")
        
        if not result:
            raise HTTPException(status_code=500, detail="Failed to execute project")
        
        # Get the created agents for debugging
        project_agents = [a for a in orchestrator.agents.values() if a.project_id == project_id]
        
        return {
            "message": "Project execution started",
            "project_id": project_id,
            "status": "executing",
            "agents_created": len(project_agents),
            "agent_details": [{"id": a.id, "role": a.role.value, "status": a.status.value} for a in project_agents]
        }
    except Exception as e:
        print(f"API: Exception during execution: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Execution failed: {str(e)}")

@router.patch("/{project_id}", response_model=Project)
async def update_project(project_id: str, project_update: ProjectUpdate):
    """Update a project with partial data"""
    project = await project_service.get_project(project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    # Update only the provided fields
    update_data = project_update.dict(exclude_unset=True)
    for field, value in update_data.items():
        setattr(project, field, value)
    
    project.updated_at = datetime.now()
    
    # Update the project in storage
    await project_service.update_project(project)
    
    return project
